GET http://localhost:3001/order
###
GET http://localhost:3001/recipe/60c3e80d8b6d430bed1b7892

###
POST http://localhost:3001/recipe/60c3e80d8b6d430bed1b7892
content-type: application/json

{
    "steps": [
        {
            "name": "Step 2",
            "checked": false
        }
    ]
}